import * as d from "./db.js"; import {jobs,pets,gifts} from "./catalog.js"; import {anya} from "./anya.js";
const dur=ms=>{let s=Math.floor(ms/1000),m=Math.floor(s/60),h=Math.floor(m/60);return h+"h "+m%60+"min"};
const men= n=>"╭━━━〔 🌸 𝐀𝐍𝐘𝐀 𝐁𝐎𝐓 〕━━━╮\n┃ Oiiie @"+n+"!! 👋🥜\n┃ Anya tem MUITA coisa legal!! ✨\n┃ Waku waku!! (≧▽≦)\n┣━━〔 🎮 𝐀𝐑𝐂𝐀𝐃𝐄 〕━━┫\n┃ 🎮 .arcade\n┣━━〔 🎭 𝐑𝐏𝐆 〕━━┫\n┃ 🎭 .menurpg\n┣━━〔 🥜 𝐄𝐂𝐎𝐍𝐎𝐌𝐈𝐀 〕━━┫\n┃ 💰 .economia  💼 .empregos\n┃ 🐾 .petshop\n┣━━〔 👤 𝐒𝐎𝐂𝐈𝐀𝐋 〕━━┫\n┃ 👤 .perfil  🏆 .ranking\n┃ 🏅 .conquistas  🎁 .presentes\n┃ 🏠 .casa\n┣━━〔 💤 𝐀𝐅𝐊 〕━━┫\n┃ 💤 .afk\n┣━━〔 🛡️ 𝐀𝐃𝐌𝐈𝐍𝐈𝐒𝐓𝐑𝐀ÇÃ𝐎 〕━━┫\n┃ ⚙️ .menuadm\n┣━━〔 ℹ️ 𝐀𝐍𝐘𝐀 〕━━┫\n┃ ❓ .ajuda  🤖 .info  🏓 .ping\n┣━━━━━━━━━━━━━━━━━━━━━┫\n┃ 🥜 Moeda: Mendoim | ⭐ Alpha V0.1\n╰━━━━━━━━━━━━━━━━━━━━━╯";
const arcade="╭━━〔 🎮 ARCADE 〕━━╮\n┃ 🧠 .quiz .anagrama .charada .adivinhe .sequencia .verdadeirofalso\n┃ ⚡ .digite .palavra .emoji .inverso .rapido .complete .acerte\n┃ 🎲 .dado .moeda .roleta .sorte .caixinha\n┃ ⚔️ .ppt .duelo .corrida\n┃ 😂 .memoria .proibido .historia\n╰━━━━━━━━━━━━━━╯";
const rpg="╭━━〔 🎭 RPG SOCIAL 〕━━╮\n┃ 💕 .ship @user | 💑 .casal | 💍 .casar @user | 💔 .divorcio\n┃ 🎭 .beijar .abracar .cafune .dormir\n┃ 😂 .tapa .soco .chutar .morder .jogar\n┃ 👨‍👩‍👧 .familia .adotar .filho .mae .pai .irmao\n╰━━━━━━━━━━━━━━╯";
const adm="╭━━〔 🛡️ MENU ADM 〕━━╮\n┃ 👥 .kick .ban .promover .rebaixar .add .mutar .unmutar\n┃ 🔒 .antilink .antispam .antiflood .antipalavra .antifake .anticall .antipv .antimedia\n┃ 👋 .bemvindo .despedida .regras .setregras .autoresposta\n┃ 📢 .marcar .hidetag .marcaradmins .marcarativos .listadmins .listmembros\n┃ ⚙️ .config .configurar .prefix .logs\n┃ 🧹 .limpar .warn\n╰━━━━━━━━━━━━━━╯";
const mention=j=>"@"+j.split("@")[0];
export async function run({sock,jid,cmd,args,sender,group,participants,name}){d.user(sender,name);
if(cmd==="menu")return sock.sendMessage(jid,{text:men(name||sender.split("@")[0]),mentions:[sender]});
if(cmd==="arcade")return sock.sendMessage(jid,{text:arcade});
if(cmd==="menurpg")return sock.sendMessage(jid,{text:rpg});
if(cmd==="menuadm")return sock.sendMessage(jid,{text:adm});
if(cmd==="ping")return sock.sendMessage(jid,{text:"🏓 PONG! Anya está vivinha!! ✨"});
if(cmd==="info")return sock.sendMessage(jid,{text:"🌸 Anya Bot Alpha V0.1\nNode.js + Baileys\n🥜 Mendoins • 🎮 Arcade • 🎭 RPG"});
if(cmd==="ajuda")return sock.sendMessage(jid,{text:"❓ Use .menu para ver tudo! Waku waku! ✨"});
if(cmd==="economia"||cmd==="saldo"){let u=d.user(sender);return sock.sendMessage(jid,{text:"🥜 "+(u.name||"Você")+", você tem "+u.coins+" Mendoins!"})}
if(cmd==="daily"){try{d.coins(sender,50);d.achievement(sender,"Primeiro Mendoim");return sock.sendMessage(jid,{text:"🎁 DAILY! +50 🥜 "+anya.okmsg()})}catch{return sock.sendMessage(jid,{text:anya.errmsg()})}}
if(cmd==="perfil"){let u=d.user(args[0]||sender),p=d.pet(args[0]||sender),r=d.relation(args[0]||sender);return sock.sendMessage(jid,{text:"╭━━〔 👤 PERFIL 〕━━╮\n┃ Nome: "+(u.name||mention(u.jid))+"\n┃ 🥜 "+u.coins+" | ⭐ XP "+u.xp+" | Lv "+u.level+"\n┃ 🎮 Vitórias: "+u.wins+"\n┃ 🐾 Pet: "+(p?p.species:"nenhum")+"\n┃ 💕 Relação: "+(r?mention(r.partner):"solteiro(a)")+"\n╰━━━━━━━━━━━━━━╯",mentions:args[0]?[args[0]]:[]})}
if(cmd==="ranking"||cmd==="rankeco"){let a=d.topCoins();return sock.sendMessage(jid,{text:"🏆 RANKING\n"+a.map((u,i)=>(i+1)+". "+(u.name||mention(u.jid))+" — 🥜 "+u.coins).join("\n"),mentions:a.map(x=>x.jid)})}
if(cmd==="rankxp"){let a=d.topXp();return sock.sendMessage(jid,{text:"⭐ RANKING XP\n"+a.map((u,i)=>(i+1)+". "+(u.name||mention(u.jid))+" — "+u.xp+" XP").join("\n")})}
if(cmd==="empregos")return sock.sendMessage(jid,{text:"💼 VAGAS\n"+Object.entries(jobs).map(([k,v])=>"• .emprego "+k+" — "+v[0]+" ("+v[1]+" 🥜)").join("\n")});
if(cmd==="emprego"){let j=args[0]?.toLowerCase();if(!jobs[j])return sock.sendMessage(jid,{text:"🤔 Vaga inexistente! Use .empregos."});d.setJob(sender,j);return sock.sendMessage(jid,{text:"💼 Agora você é "+jobs[j][0]+"! Use .trabalhar."})}
if(cmd==="trabalhar"){let j=d.getJob(sender);if(!j)return sock.sendMessage(jid,{text:"🥺 Escolha um emprego primeiro."});let x=d.work(sender,jobs[j.job][1]);if(x.e==="limit")return sock.sendMessage(jid,{text:"⏰ Limite de 5 trabalhos atingido. Volte em "+dur(x.left)+"."});return sock.sendMessage(jid,{text:"💼 Trabalho feito! +"+jobs[j.job][1]+" 🥜\n"+anya.okmsg()})}
if(cmd==="petshop")return sock.sendMessage(jid,{text:"🐾 PETSHOP\n"+pets.map((p,i)=>(i+1)+". "+p[0]+" — "+p[1]+" — "+p[2]+" 🥜").join("\n")});
if(cmd==="comprarpet"){let p=pets[Number(args[0])-1];if(!p)return sock.sendMessage(jid,{text:"🐾 Use .petshop e escolha um número."});try{d.buyPet(sender,{species:p[0],rarity:p[1],price:p[2]});return sock.sendMessage(jid,{text:"🐾 Você adotou "+p[0]+"! "+anya.okmsg()})}catch{return sock.sendMessage(jid,{text:"😭 Você não tem Mendoins suficientes!"})}}
if(["pets","meupet","petstatus"].includes(cmd)){let a=d.pets(sender);return sock.sendMessage(jid,{text:a.length?a.map(p=>"🐾 "+p.species+" ["+p.rarity+"] Lv."+p.level+" | fome "+p.hunger+" | felicidade "+p.happiness).join("\n"):"🥺 Você ainda não tem pets."})}
if(["alimentar","brincar","banho","dormir","treinar"].includes(cmd)){let map={alimentar:["hunger",20],brincar:["happiness",20],banho:["happiness",5],dormir:["hp",10],treinar:["xp",10]},m=map[cmd],v=d.petAction(sender,m[0],m[1]);if(cmd==="treinar"&&v!==null)d.xp(sender,10);return sock.sendMessage(jid,{text:v===null?"🥺 Você não tem pet.":"🐾 Pet cuidado! Waku waku! ✨"})}
if(cmd==="ship"||cmd==="casar"){let t=args[0],pct=Math.floor(Math.random()*101);if(!t||t===sender)return sock.sendMessage(jid,{text:"😳 Mencione outra pessoa!"});if(cmd==="casar"){if(pct<35)return sock.sendMessage(jid,{text:"💔 Compatibilidade: "+pct+"%. Anya acha que é cedo demais..."});d.marry(sender,t);return sock.sendMessage(jid,{text:"💍 "+mention(sender)+" + "+mention(t)+" agora são casados! ❤️\nCompatibilidade: "+pct+"%",mentions:[sender,t]})}return sock.sendMessage(jid,{text:"💕 "+mention(sender)+" + "+mention(t)+" = "+pct+"%! "+(pct>80?"WAKU WAKU!! ❤️":"Anya vai observar... 👀"),mentions:[sender,t]})}
if(cmd==="casal"){if(!group)return sock.sendMessage(jid,{text:"👥 Use em um grupo!"});let a=participants.filter(x=>x!==sender),x=a[Math.floor(Math.random()*a.length)],b=a.filter(y=>y!==x)[Math.floor(Math.random()*Math.max(1,a.length-1))],pct=Math.floor(Math.random()*101);if(!x||!b)return;return sock.sendMessage(jid,{text:"💞 CASAL DO GRUPO!\n"+mention(x)+" 💕 "+mention(b)+"\nCompatibilidade: "+pct+"%\n"+(pct>75?"WAKU WAKU!! 💖":"Anya vai observar... 👀"),mentions:[x,b]})}
if(cmd==="divorcio"){let r=d.divorce(sender);return sock.sendMessage(jid,{text:r?"💔 Divórcio concluído. Anya está tristinha... 🥺":"😶 Você não está casado(a)."})}
if(cmd==="afk"){d.afkSet(sender,args.join(" ")||"sem motivo");return sock.sendMessage(jid,{text:"💤 Anya anotou! Você está AFK."})}
if(cmd==="conquistas")return sock.sendMessage(jid,{text:"🏅 "+(d.achievements(sender).map(x=>x.achievement).join("\n")||"Nenhuma ainda!")});
if(cmd==="presentes")return sock.sendMessage(jid,{text:"🎁 PRESENTES\n"+gifts.map((x,i)=>(i+1)+". "+x+" — 25 🥜").join("\n")});
if(cmd==="presente"){let t=args[0],g=gifts[(Number(args[1])||1)-1];if(!t||!g)return sock.sendMessage(jid,{text:"🎁 Use .presente @user <1-5>"});try{d.coins(sender,-25);d.raw().prepare("INSERT INTO gifts(sender,receiver,item,created) VALUES(?,?,?,?)").run(sender,t,g,d.now());return sock.sendMessage(jid,{text:"🎁 Presente enviado! "+anya.okmsg(),mentions:[t]})}catch{return sock.sendMessage(jid,{text:"😭 Você não tem Mendoins suficientes!"})}}
if(cmd==="dado"){let n=1+Math.floor(Math.random()*6);return sock.sendMessage(jid,{text:"🎲 Anya jogou o dado: "+n+"!"})}
if(cmd==="moeda")return sock.sendMessage(jid,{text:"🪙 Deu "+(Math.random()<.5?"cara":"coroa")+"!"});
if(cmd==="casa"||cmd==="comprarcasa"||cmd==="decorar"||cmd==="moradores")return sock.sendMessage(jid,{text:"🏠 Sistema de casas ativo! .casa mostra o módulo; .comprarcasa custa 1000 🥜."});
if(cmd==="mercado"||cmd==="loja"||cmd==="inventario")return sock.sendMessage(jid,{text:"🏪 Mercado/inventário: base preparada para itens e anúncios da economia."});
if(cmd==="pagar"){let t=args[0],n=Number(args[1]);if(!t||t===sender||!Number.isSafeInteger(n)||n<=0)return sock.sendMessage(jid,{text:"💸 Use .pagar @user <quantia>"});try{d.coins(sender,-n);d.coins(t,n);return sock.sendMessage(jid,{text:"💸 Pagamento de "+n+" 🥜 enviado!",mentions:[t]})}catch{return sock.sendMessage(jid,{text:"😭 Saldo insuficiente!"})}}
return false}