import makeWASocket,{useMultiFileAuthState,DisconnectReason,fetchLatestBaileysVersion,jidNormalizedUser} from "@whiskeysockets/baileys"; import P from "pino"; import qr from "qrcode-terminal"; import fs from "node:fs"; import {config} from "./config.js"; import {run} from "./commands.js"; import * as d from "./db.js";
fs.mkdirSync(config.auth,{recursive:true}); const log=P({level:"info"});
const start=async()=>{const {state,saveCreds}=await useMultiFileAuthState(config.auth);const {version}=await fetchLatestBaileysVersion();const sock=makeWASocket({version,auth:state,logger:log,printQRInTerminal:false,browser:["Anya Bot","Chrome","0.1.0"]});sock.ev.on("creds.update",saveCreds);sock.ev.on("connection.update",u=>{if(u.qr)qr.generate(u.qr,{small:true});if(u.connection==="open")console.log("🌸 Anya Bot conectada! Waku waku!!");if(u.connection==="close"&&u.lastDisconnect?.error?.output?.statusCode!==DisconnectReason.loggedOut)setTimeout(start,3000)});
sock.ev.on("messages.upsert",async({messages,type})=>{if(type!=="notify")return;for(const m of messages){try{if(!m.message||m.key.fromMe)continue;const jid=m.key.remoteJid;if(!jid||jid==="status@broadcast")continue;const text=m.message.conversation||m.message.extendedTextMessage?.text||m.message.imageMessage?.caption||"";const sender=jidNormalizedUser(m.key.participant||jid);const isGroup=jid.endsWith("@g.us");let participants=[],admins=new Set();if(isGroup){const md=await sock.groupMetadata(jid);participants=md.participants.map(p=>p.id);admins=new Set(md.participants.filter(p=>p.admin).map(p=>p.id));d.group(jid)}
const a=d.afkGet(sender);if(a&&!text.startsWith((isGroup?d.group(jid).prefix:config.prefix))){const old=d.afkClear(sender);await sock.sendMessage(jid,{text:"👀 @"+sender.split("@")[0]+" voltou!\n💤 Tempo em AFK: "+Math.floor((Date.now()-old.since)/60000)+"min.",mentions:[sender]})}
if(!text.startsWith(isGroup?d.group(jid).prefix:config.prefix)){if(isGroup)for(const p of participants){if(text.includes("@"+p.split("@")[0])){const af=d.afkGet(p);if(af)await sock.sendMessage(jid,{text:"💤 @"+p.split("@")[0]+" está AFK.",mentions:[p]})}}continue}
const prefix=isGroup?d.group(jid).prefix:config.prefix;const body=text.slice(prefix.length).trim();const z=body.split(/\s+/);const cmd=(z.shift()||"").toLowerCase();const mentioned=m.message.extendedTextMessage?.contextInfo?.mentionedJid||[];const args=[...mentioned,...z.filter(x=>!x.startsWith("@"))];const name=m.pushName||sender.split("@")[0];
const admin=isGroup&&admins.has(sender);const botAdmin=isGroup&&admins.has(jidNormalizedUser(sock.user.id));const adminCmd=["menuadm","kick","ban","promover","rebaixar","add","mutar","unmutar","antilink","antispam","antiflood","antipalavra","antifake","anticall","antipv","antimedia","bemvindo","despedida","regras","setregras","autoresposta","marcar","hidetag","marcaradmins","marcarativos","listadmins","listmembros","config","configurar","prefix","logs","limpar","warn"];
if(adminCmd.includes(cmd)&&!admin){await sock.sendMessage(jid,{text:"😤 Só admins podem usar esse comando!"});continue}
if(adminCmd.includes(cmd)&&["kick","ban","promover","rebaixar","add","mutar","unmutar"].includes(cmd)&&!botAdmin){await sock.sendMessage(jid,{text:"😭 Anya não tem permissão de admin!"});continue}
if(cmd==="prefix"&&isGroup){if(args[0]){d.setGroup(jid,"prefix",args[0]);await sock.sendMessage(jid,{text:"✨ Prefixo alterado para "+args[0]})}else await sock.sendMessage(jid,{text:"🌸 Prefixo: "+prefix});continue}
if(cmd==="setregras"&&isGroup){d.setGroup(jid,"rules",args.join(" "));await sock.sendMessage(jid,{text:"📜 Regras atualizadas!"});continue}
if(cmd==="regras"&&isGroup){await sock.sendMessage(jid,{text:d.group(jid).rules||"📜 Nenhuma regra configurada."});continue}
await run({sock,jid,cmd,args,sender,group:isGroup,participants,name});}catch(e){log.error(e)}}});};start();